'use client';
import Link from 'next/link';
import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef } from 'react';
const exceptionRows = ['₹18.20 fee not logged', 'Settlement date offset by 1 day', 'No corresponding ledger entry'];
export default function Home() {
  const ref = useRef<HTMLDivElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end end'] });
  const coinY = useTransform(scrollYProgress, [.08, .18, .3], [-350, -45, 190]);
  const coinRotate = useTransform(scrollYProgress, [.08, .3], [0, 720]);
  const coinScale = useTransform(scrollYProgress, [.08, .18, .3], [.72, 1, .62]);
  const scannerOpacity = useTransform(scrollYProgress, [.18, .26, .46], [0, 1, 1]);
  const scannerScale = useTransform(scrollYProgress, [.18, .29], [.78, 1]);
  const sealOpacity = useTransform(scrollYProgress, [.39, .5], [0, 1]);
  const sealScale = useTransform(scrollYProgress, [.39, .52], [.35, 1]);
  const chapterOne = useTransform(scrollYProgress, [.06, .1, .16], [0, 1, 0]);
  const chapterTwo = useTransform(scrollYProgress, [.17, .23, .31], [0, 1, 0]);
  const chapterThree = useTransform(scrollYProgress, [.31, .38, .46], [0, 1, 0]);
  const chapterFour = useTransform(scrollYProgress, [.46, .53, .61], [0, 1, 0]);
  const reviewOpacity = useTransform(scrollYProgress, [.31, .39, .48], [0, 1, 0]);
  return <main ref={ref} className="overflow-x-hidden bg-[#060817] text-white"><nav><span className="logo">recon<span>agent</span></span><Link href="/dashboard" className="nav-link">Open dashboard ↗</Link></nav>
    <section className="hero grid-bg"><div className="orb orb-a"/><p className="eyebrow">CHAPTER 00 · RAZORPAY AI BUILDATHON · TRACK 04</p><h1>Close your books.<br/><em>Intelligently.</em></h1><p className="hero-copy">ReconAgent finds what your finance team misses — then explains exactly why.</p><motion.div initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .35 }} className="big-stat"><span>₹2.3L</span><small>stuck in unreconciled transactions</small></motion.div><Link href="/dashboard" className="cta">Start the reconciliation <b>↓</b></Link></section>
    <section className="cinematic-scroll" aria-label="Animated settlement lifecycle"><div className="cinematic-stage"><div className="cinematic-copy"><p className="eyebrow">SCROLL THE STORY</p><h2>From payment<br/>to <em>proof.</em></h2><p>One settlement moves through the complete finance-ops loop.</p></div><div className="cinematic-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><motion.div className="settlement-core" style={{ y: coinY, rotateY: coinRotate, scale: coinScale }}><div className="core-ring ring-a"/><div className="core-ring ring-b"/><div className="core-face"><span>₹</span><b>SETTLEMENT</b><small>RAZORPAY · 4,850.00</small></div><div className="core-glint"/></motion.div><motion.div className="evidence-scanner" style={{ opacity: scannerOpacity, scale: scannerScale }}><i className="scan-laser"/><span>RETRIEVING EVIDENCE</span><b>Razorpay · Ledger · Audit</b><small>RAG evidence retrieval</small></motion.div><motion.div className="review-beacon" style={{ opacity: reviewOpacity }}>!<span>₹18.20 fee delta<br/>kept for review</span></motion.div><motion.div className="verified-seal" style={{ opacity: sealOpacity, scale: sealScale }}><i>✓</i><b>SETTLEMENT<br/>VERIFIED</b><small>Exact match · 100% confidence</small></motion.div><div className="story-voice"><motion.div style={{ opacity: chapterOne }}><b>01 — PAYMENT ARRIVES</b><p>Razorpay confirms an incoming settlement.</p></motion.div><motion.div style={{ opacity: chapterTwo }}><b>02 — AI RETRIEVES CONTEXT</b><p>Order, ledger and prior audit evidence are brought together.</p></motion.div><motion.div style={{ opacity: chapterThree }}><b>03 — RISK STAYS VISIBLE</b><p>Fee and date deltas never get silently forced.</p></motion.div><motion.div style={{ opacity: chapterFour }}><b>04 — FINANCE GETS PROOF</b><p>Only safe exact matches become audit-ready decisions.</p></motion.div></div></div><div className="cinematic-caption"><span>01 Payment received</span><span>02 Evidence retrieved</span><span>03 Human review</span><span>04 Audit proof</span></div></div></section>
    <section className="section problem"><p className="eyebrow">CHAPTER 01 · TWO SOURCES COLLIDE</p><h2>Two sources.<br/>One messy reality.</h2><div className="source-grid"><motion.div initial={{ opacity: 0, x: -90 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .35 }} transition={{ duration: .7, ease: 'easeOut' }} className="data-card"><header><i className="dot purple"/> Razorpay orders <b>50 records</b></header><Row a="recon-demo-007" b="₹338.31"/><Row a="recon-demo-014" b="₹434.84"/><Row a="recon-demo-021" b="₹81.37"/></motion.div><motion.div initial={{ opacity: 0, x: 90 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .35 }} transition={{ duration: .7, delay: .12, ease: 'easeOut' }} className="data-card"><header><i className="dot teal"/> Merchant ledger <b>46 records</b></header><Row bad a="recon-demo-007" b="₹320.11"/><Row bad a="recon-demo-014" b="Missing"/><Row a="recon-demo-021" b="₹81.37"/></motion.div></div></section>
    <section className="section engine"><p className="eyebrow">CHAPTER 02 · EVIDENCE RETRIEVAL</p><h2>Every transaction,<br/><em>understood.</em></h2><div className="scanner"><div className="scan-line"/><span>RAZORPAY</span><div className="particles">✦　✦　✦　✦　✦</div><span>LEDGER</span><strong>48 <small>records scanned</small></strong></div></section>
    <section className="section"><p className="eyebrow">CHAPTER 03 · HUMAN REVIEW</p><h2>No black boxes.<br/>Just <em>clear answers.</em></h2><div className="exceptions">{exceptionRows.map((x,i)=><motion.article initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i*.12 }} key={x}><span>0{i+1}</span><div><b>{x}</b><p>ReconAgent detected and classified this exception automatically.</p></div><i>↗</i></motion.article>)}</div></section>
    <section className="section resolution"><p className="eyebrow">CHAPTER 04 · AUDIT CLOSED</p><div className="rate">80<span>%</span></div><h2>Match rate.<br/><em>Without the manual work.</em></h2><div className="checks"><span>✓ Exact receipts reconciled</span><span>✓ Fees identified</span><span>✓ Audit trail generated</span></div></section>
    <section className="impact"><div><b>80%</b><span>match rate</span></div><div><b>10</b><span>exceptions found</span></div><div><b>6.5h</b><span>saved each month</span></div></section>
    <footer><span className="logo">recon<span>agent</span></span><h2>Make every rupee<br/><em>account for itself.</em></h2><Link href="/dashboard" className="cta">Try ReconAgent <b>→</b></Link><p>Built for Razorpay AI Buildathon · 2026</p></footer></main>;
}
function Row({a,b,bad=false}:{a:string;b:string;bad?:boolean}){return <div className={bad?'bad row':'row'}><span>{a}</span><b>{b}</b>{bad&&<i>!</i>}</div>}
